# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 552180ac48a5a448ce3f19d71fa932cca6ff405d64fa2ee161e79d7375b60507304baccae0b2e22635cc3bb0ff8b71b0f6da2080e5829ea575145889f744c284

test:
  secret_key_base: 1eca464884a69483647a9561fe3c48110aeecd58c0feeb27daac92f5ced683cc4102e625057a87ad1ec7e7224cd25a82d597b3631f1982108e737f1e6fbf4447

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
